swagger: "2.0"

info:
  title: "WIS_Grader RESTful API"
  description: "API for user authentication."
  version: "1.0.0"

paths:
  /api/v1/login:
    post:
      tags:
        - "Authentication"
      summary: "Login to the system"
      description: "Authenticate user by email and password to get an access token."
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: "Login credentials"
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                description: "User's email"
                example: "johndoe@example.com"
              password:
                type: string
                description: "User's password"
                example: "password123"
      responses:
        '200':
          description: "Login successful"
          schema:
            type: object
            properties:
              status:
                type: string
                example: "Success"
                description: "Indicates the status of the request"
              message:
                type: string
                example: "Login successful"
              access_token:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: "Invalid request data"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "No input data provided"
        '401':
          description: "Invalid email or password"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid email or password"

